jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '11

          17

          '
    - continue-on-error: true
      name: Print debug info
      run: 'echo "Printing env PATH var"

        echo $PATH

        echo "Printing Gradle Wrapper version"

        ./gradlew --version

        '
    - continue-on-error: true
      name: Build & run tests
      run: ./ci/build-and-test.sh
    - continue-on-error: true
      name: Copy Results
      run: 'mkdir -p ./gh_actions/test-results/junit

        find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ./gh_actions/test-results/junit
        \;

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        path: ./gh_actions/test-results
name: facebook/fresco/build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
